// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wire.proto

#ifndef PROTOBUF_wire_2eproto__INCLUDED
#define PROTOBUF_wire_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace wire {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_wire_2eproto();
void protobuf_AssignDesc_wire_2eproto();
void protobuf_ShutdownFile_wire_2eproto();

class ClientQuickUpdate;
class ServerQuickUpdate;
class ServerQuickUpdate_PlayerUpdate;
class Team;
class Score;
class Score_MetaPlayer;
class Chunk;
class Object;
class ServerUpdate;

// ===================================================================

class ClientQuickUpdate : public ::google::protobuf::Message {
 public:
  ClientQuickUpdate();
  virtual ~ClientQuickUpdate();
  
  ClientQuickUpdate(const ClientQuickUpdate& from);
  
  inline ClientQuickUpdate& operator=(const ClientQuickUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientQuickUpdate& default_instance();
  
  void Swap(ClientQuickUpdate* other);
  
  // implements Message ----------------------------------------------
  
  ClientQuickUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientQuickUpdate& from);
  void MergeFrom(const ClientQuickUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required sint32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);
  
  // required sint32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);
  
  // required float angle = 3;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 3;
  inline float angle() const;
  inline void set_angle(float value);
  
  // required float velocityX = 4;
  inline bool has_velocityx() const;
  inline void clear_velocityx();
  static const int kVelocityXFieldNumber = 4;
  inline float velocityx() const;
  inline void set_velocityx(float value);
  
  // required float velocityY = 5;
  inline bool has_velocityy() const;
  inline void clear_velocityy();
  static const int kVelocityYFieldNumber = 5;
  inline float velocityy() const;
  inline void set_velocityy(float value);
  
  // required bool isFiringFlamethrower = 6;
  inline bool has_isfiringflamethrower() const;
  inline void clear_isfiringflamethrower();
  static const int kIsFiringFlamethrowerFieldNumber = 6;
  inline bool isfiringflamethrower() const;
  inline void set_isfiringflamethrower(bool value);
  
  // optional sint32 viewportX = 7;
  inline bool has_viewportx() const;
  inline void clear_viewportx();
  static const int kViewportXFieldNumber = 7;
  inline ::google::protobuf::int32 viewportx() const;
  inline void set_viewportx(::google::protobuf::int32 value);
  
  // optional sint32 viewportY = 8;
  inline bool has_viewporty() const;
  inline void clear_viewporty();
  static const int kViewportYFieldNumber = 8;
  inline ::google::protobuf::int32 viewporty() const;
  inline void set_viewporty(::google::protobuf::int32 value);
  
  // optional sint32 viewportWidth = 9;
  inline bool has_viewportwidth() const;
  inline void clear_viewportwidth();
  static const int kViewportWidthFieldNumber = 9;
  inline ::google::protobuf::int32 viewportwidth() const;
  inline void set_viewportwidth(::google::protobuf::int32 value);
  
  // optional sint32 viewportHeight = 10;
  inline bool has_viewportheight() const;
  inline void clear_viewportheight();
  static const int kViewportHeightFieldNumber = 10;
  inline ::google::protobuf::int32 viewportheight() const;
  inline void set_viewportheight(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:wire.ClientQuickUpdate)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_angle();
  inline void clear_has_angle();
  inline void set_has_velocityx();
  inline void clear_has_velocityx();
  inline void set_has_velocityy();
  inline void clear_has_velocityy();
  inline void set_has_isfiringflamethrower();
  inline void clear_has_isfiringflamethrower();
  inline void set_has_viewportx();
  inline void clear_has_viewportx();
  inline void set_has_viewporty();
  inline void clear_has_viewporty();
  inline void set_has_viewportwidth();
  inline void clear_has_viewportwidth();
  inline void set_has_viewportheight();
  inline void clear_has_viewportheight();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  float angle_;
  float velocityx_;
  float velocityy_;
  bool isfiringflamethrower_;
  ::google::protobuf::int32 viewportx_;
  ::google::protobuf::int32 viewporty_;
  ::google::protobuf::int32 viewportwidth_;
  ::google::protobuf::int32 viewportheight_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static ClientQuickUpdate* default_instance_;
};
// -------------------------------------------------------------------

class ServerQuickUpdate_PlayerUpdate : public ::google::protobuf::Message {
 public:
  ServerQuickUpdate_PlayerUpdate();
  virtual ~ServerQuickUpdate_PlayerUpdate();
  
  ServerQuickUpdate_PlayerUpdate(const ServerQuickUpdate_PlayerUpdate& from);
  
  inline ServerQuickUpdate_PlayerUpdate& operator=(const ServerQuickUpdate_PlayerUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerQuickUpdate_PlayerUpdate& default_instance();
  
  void Swap(ServerQuickUpdate_PlayerUpdate* other);
  
  // implements Message ----------------------------------------------
  
  ServerQuickUpdate_PlayerUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerQuickUpdate_PlayerUpdate& from);
  void MergeFrom(const ServerQuickUpdate_PlayerUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 playerID = 1;
  inline bool has_playerid() const;
  inline void clear_playerid();
  static const int kPlayerIDFieldNumber = 1;
  inline ::google::protobuf::uint32 playerid() const;
  inline void set_playerid(::google::protobuf::uint32 value);
  
  // required .wire.ClientQuickUpdate update = 2;
  inline bool has_update() const;
  inline void clear_update();
  static const int kUpdateFieldNumber = 2;
  inline const ::wire::ClientQuickUpdate& update() const;
  inline ::wire::ClientQuickUpdate* mutable_update();
  inline ::wire::ClientQuickUpdate* release_update();
  
  // @@protoc_insertion_point(class_scope:wire.ServerQuickUpdate.PlayerUpdate)
 private:
  inline void set_has_playerid();
  inline void clear_has_playerid();
  inline void set_has_update();
  inline void clear_has_update();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::wire::ClientQuickUpdate* update_;
  ::google::protobuf::uint32 playerid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static ServerQuickUpdate_PlayerUpdate* default_instance_;
};
// -------------------------------------------------------------------

class ServerQuickUpdate : public ::google::protobuf::Message {
 public:
  ServerQuickUpdate();
  virtual ~ServerQuickUpdate();
  
  ServerQuickUpdate(const ServerQuickUpdate& from);
  
  inline ServerQuickUpdate& operator=(const ServerQuickUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerQuickUpdate& default_instance();
  
  void Swap(ServerQuickUpdate* other);
  
  // implements Message ----------------------------------------------
  
  ServerQuickUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerQuickUpdate& from);
  void MergeFrom(const ServerQuickUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ServerQuickUpdate_PlayerUpdate PlayerUpdate;
  
  // accessors -------------------------------------------------------
  
  // repeated .wire.ServerQuickUpdate.PlayerUpdate updates = 1;
  inline int updates_size() const;
  inline void clear_updates();
  static const int kUpdatesFieldNumber = 1;
  inline const ::wire::ServerQuickUpdate_PlayerUpdate& updates(int index) const;
  inline ::wire::ServerQuickUpdate_PlayerUpdate* mutable_updates(int index);
  inline ::wire::ServerQuickUpdate_PlayerUpdate* add_updates();
  inline const ::google::protobuf::RepeatedPtrField< ::wire::ServerQuickUpdate_PlayerUpdate >&
      updates() const;
  inline ::google::protobuf::RepeatedPtrField< ::wire::ServerQuickUpdate_PlayerUpdate >*
      mutable_updates();
  
  // @@protoc_insertion_point(class_scope:wire.ServerQuickUpdate)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::wire::ServerQuickUpdate_PlayerUpdate > updates_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static ServerQuickUpdate* default_instance_;
};
// -------------------------------------------------------------------

class Team : public ::google::protobuf::Message {
 public:
  Team();
  virtual ~Team();
  
  Team(const Team& from);
  
  inline Team& operator=(const Team& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Team& default_instance();
  
  void Swap(Team* other);
  
  // implements Message ----------------------------------------------
  
  Team* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Team& from);
  void MergeFrom(const Team& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 tickets = 1;
  inline bool has_tickets() const;
  inline void clear_tickets();
  static const int kTicketsFieldNumber = 1;
  inline ::google::protobuf::int32 tickets() const;
  inline void set_tickets(::google::protobuf::int32 value);
  
  // repeated int32 members = 2 [packed = true];
  inline int members_size() const;
  inline void clear_members();
  static const int kMembersFieldNumber = 2;
  inline ::google::protobuf::int32 members(int index) const;
  inline void set_members(int index, ::google::protobuf::int32 value);
  inline void add_members(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      members() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_members();
  
  // @@protoc_insertion_point(class_scope:wire.Team)
 private:
  inline void set_has_tickets();
  inline void clear_has_tickets();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > members_;
  mutable int _members_cached_byte_size_;
  ::google::protobuf::int32 tickets_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static Team* default_instance_;
};
// -------------------------------------------------------------------

class Score_MetaPlayer : public ::google::protobuf::Message {
 public:
  Score_MetaPlayer();
  virtual ~Score_MetaPlayer();
  
  Score_MetaPlayer(const Score_MetaPlayer& from);
  
  inline Score_MetaPlayer& operator=(const Score_MetaPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Score_MetaPlayer& default_instance();
  
  void Swap(Score_MetaPlayer* other);
  
  // implements Message ----------------------------------------------
  
  Score_MetaPlayer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Score_MetaPlayer& from);
  void MergeFrom(const Score_MetaPlayer& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 kills = 1;
  inline bool has_kills() const;
  inline void clear_kills();
  static const int kKillsFieldNumber = 1;
  inline ::google::protobuf::int32 kills() const;
  inline void set_kills(::google::protobuf::int32 value);
  
  // required int32 deaths = 2;
  inline bool has_deaths() const;
  inline void clear_deaths();
  static const int kDeathsFieldNumber = 2;
  inline ::google::protobuf::int32 deaths() const;
  inline void set_deaths(::google::protobuf::int32 value);
  
  // optional int32 health = 3;
  inline bool has_health() const;
  inline void clear_health();
  static const int kHealthFieldNumber = 3;
  inline ::google::protobuf::int32 health() const;
  inline void set_health(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:wire.Score.MetaPlayer)
 private:
  inline void set_has_kills();
  inline void clear_has_kills();
  inline void set_has_deaths();
  inline void clear_has_deaths();
  inline void set_has_health();
  inline void clear_has_health();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 kills_;
  ::google::protobuf::int32 deaths_;
  ::google::protobuf::int32 health_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static Score_MetaPlayer* default_instance_;
};
// -------------------------------------------------------------------

class Score : public ::google::protobuf::Message {
 public:
  Score();
  virtual ~Score();
  
  Score(const Score& from);
  
  inline Score& operator=(const Score& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Score& default_instance();
  
  void Swap(Score* other);
  
  // implements Message ----------------------------------------------
  
  Score* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Score& from);
  void MergeFrom(const Score& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef Score_MetaPlayer MetaPlayer;
  
  // accessors -------------------------------------------------------
  
  // required .wire.Team red = 1;
  inline bool has_red() const;
  inline void clear_red();
  static const int kRedFieldNumber = 1;
  inline const ::wire::Team& red() const;
  inline ::wire::Team* mutable_red();
  inline ::wire::Team* release_red();
  
  // required .wire.Team blu = 2;
  inline bool has_blu() const;
  inline void clear_blu();
  static const int kBluFieldNumber = 2;
  inline const ::wire::Team& blu() const;
  inline ::wire::Team* mutable_blu();
  inline ::wire::Team* release_blu();
  
  // repeated .wire.Score.MetaPlayer metaplayers = 3;
  inline int metaplayers_size() const;
  inline void clear_metaplayers();
  static const int kMetaplayersFieldNumber = 3;
  inline const ::wire::Score_MetaPlayer& metaplayers(int index) const;
  inline ::wire::Score_MetaPlayer* mutable_metaplayers(int index);
  inline ::wire::Score_MetaPlayer* add_metaplayers();
  inline const ::google::protobuf::RepeatedPtrField< ::wire::Score_MetaPlayer >&
      metaplayers() const;
  inline ::google::protobuf::RepeatedPtrField< ::wire::Score_MetaPlayer >*
      mutable_metaplayers();
  
  // @@protoc_insertion_point(class_scope:wire.Score)
 private:
  inline void set_has_red();
  inline void clear_has_red();
  inline void set_has_blu();
  inline void clear_has_blu();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::wire::Team* red_;
  ::wire::Team* blu_;
  ::google::protobuf::RepeatedPtrField< ::wire::Score_MetaPlayer > metaplayers_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static Score* default_instance_;
};
// -------------------------------------------------------------------

class Chunk : public ::google::protobuf::Message {
 public:
  Chunk();
  virtual ~Chunk();
  
  Chunk(const Chunk& from);
  
  inline Chunk& operator=(const Chunk& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Chunk& default_instance();
  
  void Swap(Chunk* other);
  
  // implements Message ----------------------------------------------
  
  Chunk* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Chunk& from);
  void MergeFrom(const Chunk& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required sint32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);
  
  // required sint32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);
  
  // required int32 version = 3;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 3;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);
  
  // optional bytes tiles = 4;
  inline bool has_tiles() const;
  inline void clear_tiles();
  static const int kTilesFieldNumber = 4;
  inline const ::std::string& tiles() const;
  inline void set_tiles(const ::std::string& value);
  inline void set_tiles(const char* value);
  inline void set_tiles(const void* value, size_t size);
  inline ::std::string* mutable_tiles();
  inline ::std::string* release_tiles();
  
  // optional bytes metadata = 5;
  inline bool has_metadata() const;
  inline void clear_metadata();
  static const int kMetadataFieldNumber = 5;
  inline const ::std::string& metadata() const;
  inline void set_metadata(const ::std::string& value);
  inline void set_metadata(const char* value);
  inline void set_metadata(const void* value, size_t size);
  inline ::std::string* mutable_metadata();
  inline ::std::string* release_metadata();
  
  // @@protoc_insertion_point(class_scope:wire.Chunk)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_tiles();
  inline void clear_has_tiles();
  inline void set_has_metadata();
  inline void clear_has_metadata();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::std::string* tiles_;
  ::std::string* metadata_;
  ::google::protobuf::int32 version_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static Chunk* default_instance_;
};
// -------------------------------------------------------------------

class Object : public ::google::protobuf::Message {
 public:
  Object();
  virtual ~Object();
  
  Object(const Object& from);
  
  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Object& default_instance();
  
  void Swap(Object* other);
  
  // implements Message ----------------------------------------------
  
  Object* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required sint32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);
  
  // required sint32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);
  
  // required sint32 angle = 3;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 3;
  inline ::google::protobuf::int32 angle() const;
  inline void set_angle(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:wire.Object)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_angle();
  inline void clear_has_angle();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 angle_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static Object* default_instance_;
};
// -------------------------------------------------------------------

class ServerUpdate : public ::google::protobuf::Message {
 public:
  ServerUpdate();
  virtual ~ServerUpdate();
  
  ServerUpdate(const ServerUpdate& from);
  
  inline ServerUpdate& operator=(const ServerUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerUpdate& default_instance();
  
  void Swap(ServerUpdate* other);
  
  // implements Message ----------------------------------------------
  
  ServerUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerUpdate& from);
  void MergeFrom(const ServerUpdate& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .wire.Chunk chunks = 1;
  inline int chunks_size() const;
  inline void clear_chunks();
  static const int kChunksFieldNumber = 1;
  inline const ::wire::Chunk& chunks(int index) const;
  inline ::wire::Chunk* mutable_chunks(int index);
  inline ::wire::Chunk* add_chunks();
  inline const ::google::protobuf::RepeatedPtrField< ::wire::Chunk >&
      chunks() const;
  inline ::google::protobuf::RepeatedPtrField< ::wire::Chunk >*
      mutable_chunks();
  
  // repeated .wire.Object objects = 2;
  inline int objects_size() const;
  inline void clear_objects();
  static const int kObjectsFieldNumber = 2;
  inline const ::wire::Object& objects(int index) const;
  inline ::wire::Object* mutable_objects(int index);
  inline ::wire::Object* add_objects();
  inline const ::google::protobuf::RepeatedPtrField< ::wire::Object >&
      objects() const;
  inline ::google::protobuf::RepeatedPtrField< ::wire::Object >*
      mutable_objects();
  
  // @@protoc_insertion_point(class_scope:wire.ServerUpdate)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::wire::Chunk > chunks_;
  ::google::protobuf::RepeatedPtrField< ::wire::Object > objects_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_wire_2eproto();
  friend void protobuf_AssignDesc_wire_2eproto();
  friend void protobuf_ShutdownFile_wire_2eproto();
  
  void InitAsDefaultInstance();
  static ServerUpdate* default_instance_;
};
// ===================================================================


// ===================================================================

// ClientQuickUpdate

// required sint32 x = 1;
inline bool ClientQuickUpdate::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientQuickUpdate::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientQuickUpdate::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientQuickUpdate::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 ClientQuickUpdate::x() const {
  return x_;
}
inline void ClientQuickUpdate::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required sint32 y = 2;
inline bool ClientQuickUpdate::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientQuickUpdate::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientQuickUpdate::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientQuickUpdate::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 ClientQuickUpdate::y() const {
  return y_;
}
inline void ClientQuickUpdate::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// required float angle = 3;
inline bool ClientQuickUpdate::has_angle() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ClientQuickUpdate::set_has_angle() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ClientQuickUpdate::clear_has_angle() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ClientQuickUpdate::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline float ClientQuickUpdate::angle() const {
  return angle_;
}
inline void ClientQuickUpdate::set_angle(float value) {
  set_has_angle();
  angle_ = value;
}

// required float velocityX = 4;
inline bool ClientQuickUpdate::has_velocityx() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ClientQuickUpdate::set_has_velocityx() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ClientQuickUpdate::clear_has_velocityx() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ClientQuickUpdate::clear_velocityx() {
  velocityx_ = 0;
  clear_has_velocityx();
}
inline float ClientQuickUpdate::velocityx() const {
  return velocityx_;
}
inline void ClientQuickUpdate::set_velocityx(float value) {
  set_has_velocityx();
  velocityx_ = value;
}

// required float velocityY = 5;
inline bool ClientQuickUpdate::has_velocityy() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ClientQuickUpdate::set_has_velocityy() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ClientQuickUpdate::clear_has_velocityy() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ClientQuickUpdate::clear_velocityy() {
  velocityy_ = 0;
  clear_has_velocityy();
}
inline float ClientQuickUpdate::velocityy() const {
  return velocityy_;
}
inline void ClientQuickUpdate::set_velocityy(float value) {
  set_has_velocityy();
  velocityy_ = value;
}

// required bool isFiringFlamethrower = 6;
inline bool ClientQuickUpdate::has_isfiringflamethrower() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ClientQuickUpdate::set_has_isfiringflamethrower() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ClientQuickUpdate::clear_has_isfiringflamethrower() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ClientQuickUpdate::clear_isfiringflamethrower() {
  isfiringflamethrower_ = false;
  clear_has_isfiringflamethrower();
}
inline bool ClientQuickUpdate::isfiringflamethrower() const {
  return isfiringflamethrower_;
}
inline void ClientQuickUpdate::set_isfiringflamethrower(bool value) {
  set_has_isfiringflamethrower();
  isfiringflamethrower_ = value;
}

// optional sint32 viewportX = 7;
inline bool ClientQuickUpdate::has_viewportx() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ClientQuickUpdate::set_has_viewportx() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ClientQuickUpdate::clear_has_viewportx() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ClientQuickUpdate::clear_viewportx() {
  viewportx_ = 0;
  clear_has_viewportx();
}
inline ::google::protobuf::int32 ClientQuickUpdate::viewportx() const {
  return viewportx_;
}
inline void ClientQuickUpdate::set_viewportx(::google::protobuf::int32 value) {
  set_has_viewportx();
  viewportx_ = value;
}

// optional sint32 viewportY = 8;
inline bool ClientQuickUpdate::has_viewporty() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ClientQuickUpdate::set_has_viewporty() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ClientQuickUpdate::clear_has_viewporty() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ClientQuickUpdate::clear_viewporty() {
  viewporty_ = 0;
  clear_has_viewporty();
}
inline ::google::protobuf::int32 ClientQuickUpdate::viewporty() const {
  return viewporty_;
}
inline void ClientQuickUpdate::set_viewporty(::google::protobuf::int32 value) {
  set_has_viewporty();
  viewporty_ = value;
}

// optional sint32 viewportWidth = 9;
inline bool ClientQuickUpdate::has_viewportwidth() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ClientQuickUpdate::set_has_viewportwidth() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ClientQuickUpdate::clear_has_viewportwidth() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ClientQuickUpdate::clear_viewportwidth() {
  viewportwidth_ = 0;
  clear_has_viewportwidth();
}
inline ::google::protobuf::int32 ClientQuickUpdate::viewportwidth() const {
  return viewportwidth_;
}
inline void ClientQuickUpdate::set_viewportwidth(::google::protobuf::int32 value) {
  set_has_viewportwidth();
  viewportwidth_ = value;
}

// optional sint32 viewportHeight = 10;
inline bool ClientQuickUpdate::has_viewportheight() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ClientQuickUpdate::set_has_viewportheight() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ClientQuickUpdate::clear_has_viewportheight() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ClientQuickUpdate::clear_viewportheight() {
  viewportheight_ = 0;
  clear_has_viewportheight();
}
inline ::google::protobuf::int32 ClientQuickUpdate::viewportheight() const {
  return viewportheight_;
}
inline void ClientQuickUpdate::set_viewportheight(::google::protobuf::int32 value) {
  set_has_viewportheight();
  viewportheight_ = value;
}

// -------------------------------------------------------------------

// ServerQuickUpdate_PlayerUpdate

// required uint32 playerID = 1;
inline bool ServerQuickUpdate_PlayerUpdate::has_playerid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerQuickUpdate_PlayerUpdate::set_has_playerid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerQuickUpdate_PlayerUpdate::clear_has_playerid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerQuickUpdate_PlayerUpdate::clear_playerid() {
  playerid_ = 0u;
  clear_has_playerid();
}
inline ::google::protobuf::uint32 ServerQuickUpdate_PlayerUpdate::playerid() const {
  return playerid_;
}
inline void ServerQuickUpdate_PlayerUpdate::set_playerid(::google::protobuf::uint32 value) {
  set_has_playerid();
  playerid_ = value;
}

// required .wire.ClientQuickUpdate update = 2;
inline bool ServerQuickUpdate_PlayerUpdate::has_update() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerQuickUpdate_PlayerUpdate::set_has_update() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerQuickUpdate_PlayerUpdate::clear_has_update() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerQuickUpdate_PlayerUpdate::clear_update() {
  if (update_ != NULL) update_->::wire::ClientQuickUpdate::Clear();
  clear_has_update();
}
inline const ::wire::ClientQuickUpdate& ServerQuickUpdate_PlayerUpdate::update() const {
  return update_ != NULL ? *update_ : *default_instance_->update_;
}
inline ::wire::ClientQuickUpdate* ServerQuickUpdate_PlayerUpdate::mutable_update() {
  set_has_update();
  if (update_ == NULL) update_ = new ::wire::ClientQuickUpdate;
  return update_;
}
inline ::wire::ClientQuickUpdate* ServerQuickUpdate_PlayerUpdate::release_update() {
  clear_has_update();
  ::wire::ClientQuickUpdate* temp = update_;
  update_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// ServerQuickUpdate

// repeated .wire.ServerQuickUpdate.PlayerUpdate updates = 1;
inline int ServerQuickUpdate::updates_size() const {
  return updates_.size();
}
inline void ServerQuickUpdate::clear_updates() {
  updates_.Clear();
}
inline const ::wire::ServerQuickUpdate_PlayerUpdate& ServerQuickUpdate::updates(int index) const {
  return updates_.Get(index);
}
inline ::wire::ServerQuickUpdate_PlayerUpdate* ServerQuickUpdate::mutable_updates(int index) {
  return updates_.Mutable(index);
}
inline ::wire::ServerQuickUpdate_PlayerUpdate* ServerQuickUpdate::add_updates() {
  return updates_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wire::ServerQuickUpdate_PlayerUpdate >&
ServerQuickUpdate::updates() const {
  return updates_;
}
inline ::google::protobuf::RepeatedPtrField< ::wire::ServerQuickUpdate_PlayerUpdate >*
ServerQuickUpdate::mutable_updates() {
  return &updates_;
}

// -------------------------------------------------------------------

// Team

// required int32 tickets = 1;
inline bool Team::has_tickets() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Team::set_has_tickets() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Team::clear_has_tickets() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Team::clear_tickets() {
  tickets_ = 0;
  clear_has_tickets();
}
inline ::google::protobuf::int32 Team::tickets() const {
  return tickets_;
}
inline void Team::set_tickets(::google::protobuf::int32 value) {
  set_has_tickets();
  tickets_ = value;
}

// repeated int32 members = 2 [packed = true];
inline int Team::members_size() const {
  return members_.size();
}
inline void Team::clear_members() {
  members_.Clear();
}
inline ::google::protobuf::int32 Team::members(int index) const {
  return members_.Get(index);
}
inline void Team::set_members(int index, ::google::protobuf::int32 value) {
  members_.Set(index, value);
}
inline void Team::add_members(::google::protobuf::int32 value) {
  members_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Team::members() const {
  return members_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Team::mutable_members() {
  return &members_;
}

// -------------------------------------------------------------------

// Score_MetaPlayer

// required int32 kills = 1;
inline bool Score_MetaPlayer::has_kills() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Score_MetaPlayer::set_has_kills() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Score_MetaPlayer::clear_has_kills() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Score_MetaPlayer::clear_kills() {
  kills_ = 0;
  clear_has_kills();
}
inline ::google::protobuf::int32 Score_MetaPlayer::kills() const {
  return kills_;
}
inline void Score_MetaPlayer::set_kills(::google::protobuf::int32 value) {
  set_has_kills();
  kills_ = value;
}

// required int32 deaths = 2;
inline bool Score_MetaPlayer::has_deaths() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Score_MetaPlayer::set_has_deaths() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Score_MetaPlayer::clear_has_deaths() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Score_MetaPlayer::clear_deaths() {
  deaths_ = 0;
  clear_has_deaths();
}
inline ::google::protobuf::int32 Score_MetaPlayer::deaths() const {
  return deaths_;
}
inline void Score_MetaPlayer::set_deaths(::google::protobuf::int32 value) {
  set_has_deaths();
  deaths_ = value;
}

// optional int32 health = 3;
inline bool Score_MetaPlayer::has_health() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Score_MetaPlayer::set_has_health() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Score_MetaPlayer::clear_has_health() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Score_MetaPlayer::clear_health() {
  health_ = 0;
  clear_has_health();
}
inline ::google::protobuf::int32 Score_MetaPlayer::health() const {
  return health_;
}
inline void Score_MetaPlayer::set_health(::google::protobuf::int32 value) {
  set_has_health();
  health_ = value;
}

// -------------------------------------------------------------------

// Score

// required .wire.Team red = 1;
inline bool Score::has_red() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Score::set_has_red() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Score::clear_has_red() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Score::clear_red() {
  if (red_ != NULL) red_->::wire::Team::Clear();
  clear_has_red();
}
inline const ::wire::Team& Score::red() const {
  return red_ != NULL ? *red_ : *default_instance_->red_;
}
inline ::wire::Team* Score::mutable_red() {
  set_has_red();
  if (red_ == NULL) red_ = new ::wire::Team;
  return red_;
}
inline ::wire::Team* Score::release_red() {
  clear_has_red();
  ::wire::Team* temp = red_;
  red_ = NULL;
  return temp;
}

// required .wire.Team blu = 2;
inline bool Score::has_blu() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Score::set_has_blu() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Score::clear_has_blu() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Score::clear_blu() {
  if (blu_ != NULL) blu_->::wire::Team::Clear();
  clear_has_blu();
}
inline const ::wire::Team& Score::blu() const {
  return blu_ != NULL ? *blu_ : *default_instance_->blu_;
}
inline ::wire::Team* Score::mutable_blu() {
  set_has_blu();
  if (blu_ == NULL) blu_ = new ::wire::Team;
  return blu_;
}
inline ::wire::Team* Score::release_blu() {
  clear_has_blu();
  ::wire::Team* temp = blu_;
  blu_ = NULL;
  return temp;
}

// repeated .wire.Score.MetaPlayer metaplayers = 3;
inline int Score::metaplayers_size() const {
  return metaplayers_.size();
}
inline void Score::clear_metaplayers() {
  metaplayers_.Clear();
}
inline const ::wire::Score_MetaPlayer& Score::metaplayers(int index) const {
  return metaplayers_.Get(index);
}
inline ::wire::Score_MetaPlayer* Score::mutable_metaplayers(int index) {
  return metaplayers_.Mutable(index);
}
inline ::wire::Score_MetaPlayer* Score::add_metaplayers() {
  return metaplayers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wire::Score_MetaPlayer >&
Score::metaplayers() const {
  return metaplayers_;
}
inline ::google::protobuf::RepeatedPtrField< ::wire::Score_MetaPlayer >*
Score::mutable_metaplayers() {
  return &metaplayers_;
}

// -------------------------------------------------------------------

// Chunk

// required sint32 x = 1;
inline bool Chunk::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Chunk::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Chunk::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Chunk::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Chunk::x() const {
  return x_;
}
inline void Chunk::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required sint32 y = 2;
inline bool Chunk::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Chunk::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Chunk::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Chunk::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Chunk::y() const {
  return y_;
}
inline void Chunk::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// required int32 version = 3;
inline bool Chunk::has_version() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Chunk::set_has_version() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Chunk::clear_has_version() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Chunk::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::google::protobuf::int32 Chunk::version() const {
  return version_;
}
inline void Chunk::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
}

// optional bytes tiles = 4;
inline bool Chunk::has_tiles() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Chunk::set_has_tiles() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Chunk::clear_has_tiles() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Chunk::clear_tiles() {
  if (tiles_ != &::google::protobuf::internal::kEmptyString) {
    tiles_->clear();
  }
  clear_has_tiles();
}
inline const ::std::string& Chunk::tiles() const {
  return *tiles_;
}
inline void Chunk::set_tiles(const ::std::string& value) {
  set_has_tiles();
  if (tiles_ == &::google::protobuf::internal::kEmptyString) {
    tiles_ = new ::std::string;
  }
  tiles_->assign(value);
}
inline void Chunk::set_tiles(const char* value) {
  set_has_tiles();
  if (tiles_ == &::google::protobuf::internal::kEmptyString) {
    tiles_ = new ::std::string;
  }
  tiles_->assign(value);
}
inline void Chunk::set_tiles(const void* value, size_t size) {
  set_has_tiles();
  if (tiles_ == &::google::protobuf::internal::kEmptyString) {
    tiles_ = new ::std::string;
  }
  tiles_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Chunk::mutable_tiles() {
  set_has_tiles();
  if (tiles_ == &::google::protobuf::internal::kEmptyString) {
    tiles_ = new ::std::string;
  }
  return tiles_;
}
inline ::std::string* Chunk::release_tiles() {
  clear_has_tiles();
  if (tiles_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = tiles_;
    tiles_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bytes metadata = 5;
inline bool Chunk::has_metadata() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Chunk::set_has_metadata() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Chunk::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Chunk::clear_metadata() {
  if (metadata_ != &::google::protobuf::internal::kEmptyString) {
    metadata_->clear();
  }
  clear_has_metadata();
}
inline const ::std::string& Chunk::metadata() const {
  return *metadata_;
}
inline void Chunk::set_metadata(const ::std::string& value) {
  set_has_metadata();
  if (metadata_ == &::google::protobuf::internal::kEmptyString) {
    metadata_ = new ::std::string;
  }
  metadata_->assign(value);
}
inline void Chunk::set_metadata(const char* value) {
  set_has_metadata();
  if (metadata_ == &::google::protobuf::internal::kEmptyString) {
    metadata_ = new ::std::string;
  }
  metadata_->assign(value);
}
inline void Chunk::set_metadata(const void* value, size_t size) {
  set_has_metadata();
  if (metadata_ == &::google::protobuf::internal::kEmptyString) {
    metadata_ = new ::std::string;
  }
  metadata_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Chunk::mutable_metadata() {
  set_has_metadata();
  if (metadata_ == &::google::protobuf::internal::kEmptyString) {
    metadata_ = new ::std::string;
  }
  return metadata_;
}
inline ::std::string* Chunk::release_metadata() {
  clear_has_metadata();
  if (metadata_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = metadata_;
    metadata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// Object

// required sint32 x = 1;
inline bool Object::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Object::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Object::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Object::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Object::x() const {
  return x_;
}
inline void Object::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required sint32 y = 2;
inline bool Object::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Object::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Object::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Object::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Object::y() const {
  return y_;
}
inline void Object::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// required sint32 angle = 3;
inline bool Object::has_angle() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Object::set_has_angle() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Object::clear_has_angle() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Object::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline ::google::protobuf::int32 Object::angle() const {
  return angle_;
}
inline void Object::set_angle(::google::protobuf::int32 value) {
  set_has_angle();
  angle_ = value;
}

// -------------------------------------------------------------------

// ServerUpdate

// repeated .wire.Chunk chunks = 1;
inline int ServerUpdate::chunks_size() const {
  return chunks_.size();
}
inline void ServerUpdate::clear_chunks() {
  chunks_.Clear();
}
inline const ::wire::Chunk& ServerUpdate::chunks(int index) const {
  return chunks_.Get(index);
}
inline ::wire::Chunk* ServerUpdate::mutable_chunks(int index) {
  return chunks_.Mutable(index);
}
inline ::wire::Chunk* ServerUpdate::add_chunks() {
  return chunks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wire::Chunk >&
ServerUpdate::chunks() const {
  return chunks_;
}
inline ::google::protobuf::RepeatedPtrField< ::wire::Chunk >*
ServerUpdate::mutable_chunks() {
  return &chunks_;
}

// repeated .wire.Object objects = 2;
inline int ServerUpdate::objects_size() const {
  return objects_.size();
}
inline void ServerUpdate::clear_objects() {
  objects_.Clear();
}
inline const ::wire::Object& ServerUpdate::objects(int index) const {
  return objects_.Get(index);
}
inline ::wire::Object* ServerUpdate::mutable_objects(int index) {
  return objects_.Mutable(index);
}
inline ::wire::Object* ServerUpdate::add_objects() {
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::wire::Object >&
ServerUpdate::objects() const {
  return objects_;
}
inline ::google::protobuf::RepeatedPtrField< ::wire::Object >*
ServerUpdate::mutable_objects() {
  return &objects_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace wire

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_wire_2eproto__INCLUDED
